#!/bin/bash

echo "Compiling..."
make

echo "Stopping CUPS"
systemctl stop cups.service

echo "Compile drivers"
ppdc *.drv

echo "Copying files"
cp rastertozj /usr/lib/cups/filter/
mkdir -p /usr/share/cups/model/zjiang
cp -v ppd/zj58.ppd /usr/share/cups/model/zjiang/
echo "Copied zjg8.ppd"
cp -v ppd/zj80.ppd /usr/share/cups/model/zjiang/
echo "Copied zj80.ppd"
cd /usr/lib/cups/filter
chmod 755 rastertozj
chown root:root rastertozj
cd -

echo "Starting CUPS"
systemctl start cups.service
